apiVersion: v1
kind: Pod

metadata:
  name: dbserver
  labels:
    app: db

spec:
  containers:
    - name: db
      image: mariadb:11.4
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root123
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: dbuser
        - name: MYSQL_PASSWORD
          value: root123
