apiVersion: apps/v1
kind: Deployment

metadata:
  name: dquota
  namespace: web
  annotations:
    kubernetes.io/change-cause: "version v1"
  labels:
    app: web

spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: vikrxnt29/nginx:v1
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 10Mi
          env:
            - name: n1
              value: v1
