apiVersion: apps/v1
kind: Deployment

metadata:
  name: dm1

spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: pods
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: n1
              value: v1
