apiVersion: v1
kind: ReplicationController 

metadata:
  name: rc
  labels:
    app: webapp

spec:
  replicas: 3
  template:
    metadata:
      name: pods
      labels:
        test: app
    spec:
      containers:
        - name: web
          image: nginx
          env:
            - name: n1
              value: v1
            - name: n2
              value: v2
          ports:
            - containerPort: 80

