
apiVersion: v1
kind: Secret

data:
  MARIADB_DATABASE: bXlkYg==
  MARIADB_USER: ZGJ1c2Vy
  MARIADB_PASSWORD: dXNlcjEyMw==
  MARIADB_ROOT_PASSWORD: cm9vdDEyMw==

metadata:
  name: dbcred
  namespace: web

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: webtest
  namespace: web
  annotations:
    kubernetes.io/change-cause: 'v1 Deployment'
  labels:
    role: webapp

spec:
  replicas: 10
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webserver
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webmount
              mountPath: /usr/share/nginx/html/
              readOnly: True
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: dbserver
          image: mariadb:11.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: dbcred
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 10Mi
      volumes:
        - name: webmount
          configMap:
            name: webpage
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:  
            - weight: 10
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - test

--- 

apiVersion: v1
kind: Service

metadata:
  name: expose
  namespace: web

spec:
  type: NodePort
  ports:
    - nodePort: 32002
      port: 80
      targetPort: 80 
  selector:
    app: webapp

