
apiVersion: v1
kind: Pod

metadata:
  name: pod4
  namespace: web
  labels:
    app: web

spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
  nodeSelector:
    role: strongl 
