

apiVersion: v1
kind: Secret

data:
  MARIADB_DATABASE: bXlkYg==
  MARIADB_USER: ZGJ1c2Vy
  MARIADB_PASSWORD: dXNlcjEyMw==
  MARIADB_ROOT_PASSWORD: cm9vdDEyMw==

metadata:
  name: dbsecret
  namespace: web

---

apiVersion: v1
kind: Pod

metadata:
  name: dbpod
  namespace: web
  labels:
    app: db

spec:
  containers:
    - name: dbserver
      image: mariadb:11.4
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: dbsecret
