apiVersion: v1
kind: Secret

data:
  MARIADB_DATABASE: bXlkYg==
  MARIADB_USER: ZGJ1c2Vy
  MARIADB_PASSWORD: YWRtaW4xMjM=
  MARIADB_ROOT_PASSWORD: cm9vdDEyMw==
      
metadata:
  name: dbcred
  namespace: web

--- 

apiVersion: apps/v1
kind: Deployment

metadata:
  name: webdeployment
  namespace: web
  annotations:
    kubernetes.io/change-cause: 'version 1 deployment'
  labels:
    role: webapp

spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      role: webapp
  template:
    metadata:
      labels:
        role: webapp
    spec:
      containers:
        - name: webserver
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webmount
              mountPath: /usr/share/nginx/html
              readOnly: True
        - name: dbserver
          image: mariadb:11.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: dbcred
      volumes:
         - name: webmount
           configMap:
             name: modpage
---

apiVersion: v1
kind: Service

metadata:
  name: expose
  namespace: web

spec:
  type: NodePort
  ports:
    - nodePort: 32002
      port: 80
      targetPort: 80
  selector:
    role: webapp

