apiVersion: v1
kind: Secret
metadata:
  name: dbcred
  namespace: web
type: Opaque
data:
  MARIADB_DATABASE: bXlkYg==
  MARIADB_USER: ZGJ1c2Vy
  MARIADB_PASSWORD: YWRtaW4xMjM=
  MARIADB_ROOT_PASSWORD: cm9vdDEyMw==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modpage
  namespace: web
data:
  index.html: |
    <html>
    <body>
      <h1>Welcome to Nginx</h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeployment
  namespace: web
  annotations:
    kubernetes.io/change-cause: "version 1 deployment"
  labels:
    role: webapp

spec:
  replicas: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0

  selector:
    matchLabels:
      role: webapp

  template:
    metadata:
      labels:
        role: webapp

    spec:
      containers:
        - name: webserver
          image: nginx:1.27
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          volumeMounts:
            - name: webmount
              mountPath: /usr/share/nginx/html
              readOnly: true

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

        - name: dbserver
          image: mariadb:11.4.7
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: dbcred

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 20

      volumes:
        - name: webmount
          configMap:
            name: modpage

---
apiVersion: v1
kind: Service
metadata:
  name: expose
  namespace: web

spec:
  type: NodePort

  ports:
    - port: 80
      targetPort: 80
      nodePort: 32002

  selector:
    role: webappe
