
apiVersion: v1
kind: Pod   

metadata:
  name: volume-pod
  namespace: web
  labels: 
    role: webapp
  
spec:
  containers:
    - name: web
      image: nginx:1.27
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: pv-pod
  nodeName: worker1.rhel9.com
  volumes:
    - name: pv-pod
      persistentVolumeClaim:
        claimName: pv-claim 
