apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "*/3 * * * *"   # Every 5 minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronjob
            image: nginx
            command:
            - /bin/sh
            - -c
            - |
              echo "CronJob started at $(date)"
              sleep 10
              echo "CronJob completed"

# useCase : It will create a pod on 3 mints and to the activity which we write on Command
