
apiVersion: apps/v1
kind: Deployment

metadata:
  name: canary
  namespace: web
  annotations: 
    kubernetes.io/change-cause: "canary version v1"

spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  selector: 
    matchLabels:
      role: canary
  template:
    metadata:
      labels:
        role: canary
    spec:
      containers:
        - name: web
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: webmount
              mountPath: /usr/share/nginx/html
              readOnly: true
          
          # Utilazation

          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 50m
              memory: 50Mi
          
          # Probes

          startupProbe:
            httpGet: 
              path: /
              port: 80
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 3
          
          livenessProbe:
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3       

      volumes:
        - name: webmount
          configMap:
            name: v1

