apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  namespace: web
spec:
  # 1. Target: What workload are we scaling?
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webhost
  
  # 2. Boundaries: Min and Max limit of Pods allowed
  minReplicas: 2
  maxReplicas: 10
  
  # 3. Triggers: When should we scale?
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale up if average CPU usage exceeds 50%
