apiVersion: v1
kind: Pod

metadata:
  name: first-toleration-delete
  namespace: web
  labels:
    app: web

spec:
  containers:
    - name: webserver
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
  tolerations:
    - effect: "NoExecute"
      key: "mysize"
      operator: "Equal"
      value: "large"
      
