apiVersion: v1
kind: Pod
  
metadata:
  name: webserver
  namespace: web
  labels:
    app: basic

spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: webmount
          mountPath: /tmp/
          readOnly: true
  volumes:
    - name: webmount
      secret:
        secretName: basic  


