apiVersion: v1
kind: Pod

metadata:
  name: allenv
  namespace: web
  labels:
    app: db

spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: byml
