apiVersion: v1
kind: Pod

metadata:
  name: keypod
  namespace: web
  labels:
    app: web1

spec:
  containers:
    - name: keycant
      image: nginx
      imagePullPolicy: IfNotPresent
      env:
        - name: dbvar                 ##  variable name inside the container
          valueFrom:
            secretKeyRef:
              key: mariadb_database   ##  variable value of this variable
              name: byml              ##  secret name
