apiVersion: v1

data:
  MARIADB_DATABASE: ZGI=
  MARIADB_USER: ZGV4dGVy
  MARIADB_PASSWORD: ZGV4dGVyMTIz 
  MARIADB_ROOT_PASSWORD: ZGV4dGVyMTIzNA==

kind: Secret

metadata:
  name: dbsec
  namespace: web
  
---

apiVersion: v1
kind: Pod

metadata: 
  name: db1
  namespace: web
  labels:
    app: db

spec:
  containers:
    - name: db
      image: mariadb:11.4
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: dbsec
