

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: state
  namespace: web

spec:
  replicas: 5
  selector:
    matchLabels:
     role: db
  template:
    metadata:
      labels:
        role: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: dbcred

