
apiVersion: v1
kind: Pod

metadata:
  name: pod-imagecheck  
  namespace: web
  labels:
    role: image-change

spec:
  containers:
    - name: web
      image: vikrxnt29/nginx:v2
      ports:
        - containerPort: 80
      