
apiVersion: v1
kind: Secret

data:
  MARIADB_PASSWORD: dXNlcjEyMw==
  MARIADB_ROOT_PASSWORD: cm9vdDEyMw==

metadata:
  name: dbcred
  namespace: web

---

apiVersion: v1
kind: ConfigMap

data:
  MARIADB_DATABASE: mydb
  MARIADB_USER: dbuser

metadata:
  name: dbinfo
  namespace: web

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: webhost
  namespace: web
  annotations:
    kubernetes.io/change-cause: 'version 1'
  labels:
    role: webapp

spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      role: webapp
  template:
    metadata:
      labels:
        role: webapp
    spec:
      containers: 
        - name: webserver
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webmount
              mountPath: /usr/share/nginx/html
              readOnly: true
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 50Mi
        - name: dbserver
          image: mariadb:11.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: dbcred
            - configMapRef:
                name: dbinfo
      volumes: 
        - name: webmount
          configMap: 
            name: modpage

---

apiVersion: v1
kind: Service

metadata:
  name: expose
  namespace: web

spec:
  type: NodePort
  ports:
    - nodePort: 32002
      port: 80
      targetPort: 80
  selector:
    role: webapp

