apiVersion: v1
kind: Pod

metadata:
  name: db
  namespace: web
  labels:
    app: db

spec:
  containers:
    - name: db
      image: mariadb:11.4
      envFrom:
        - configMapRef:
            name: dbenv

