apiVersion: v1
kind: Pod

metadata:
  name: pod4
  namespace: web
   
spec:
  containers:
    - name: web
      image: vikrxnt29/nginx:v1
      ports:
        - containerPort: 80
      volumeMounts:
        - name: test 
          mountPath: "/basic"
          readOnly: true

  volumes:
    - name: test 
      configMap:
        name: envcm    
