apiVersion: v1
kind: Pod

metadata:
  name: pod2
  namespace: web
  labels:
    app: web

spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: Never
      ports:
        - containerPort: 80
      volumeMounts:
        - name: test
          mountPath: /usr/share/nginx/html
          readOnly: true
      env:
        - configMapRef:
